apiVersion: v1
kind: Service
metadata:
  name: myapp

spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "500m"
  containers:
    envFrom:
    - configMapRef:
        name: myapp-config
    - secretRef:
        name: myapp-secret